# Generated by Django 6.0.3 on 2026-03-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(choices=[('motivacional', 'Motivacional'), ('reflexiva', 'Reflexiva'), ('humor', 'Humor'), ('triste', 'Triste')], default='motivacional', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
